apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helloworld-controller
subjects:
  - kind: ServiceAccount
    name: helloworld-controller
roleRef:
  kind: Role
  name: helloworld-controller
  apiGroup: rbac.authorization.k8s.io
